// Generated by https://github.com/xhaoh94/protogen
// DO NOT EDIT!
export namespace pb{
	export const enum Cmds {
		Test = 100,
	}
	export var cmds:{ [key: number]: string }={
		100:"Test"
	}
	export var cfgs:{ [key: string]: string[][] }={
		"Test":[["1","id","1"],["2","position","Vector3"],["3","etype","6"]],
		"Vector3":[["1","x","3"],["2","y","3"],["3","z","3"]]
	}

	export interface Test {
		id:string;
		position:Vector3;
		etype:number;
	}
	export interface Vector3 {
		x:number;
		y:number;
		z:number;
	}
}